apiVersion: apps/v1
kind: Deployment
metadata:
 name: mydeployment
spec:
 strategy:
   type: RollingUpdate
 replicas: 2
 selector:
   matchLabels:
     app: project
 template:
   metadata:
    name: myPod
    labels:
      app: project
   spec:
    containers:
    - name: myweb
      image: pavankumar22/webappimage
      imagePullPolicy: Always
      ports:
      - containerPort: 80
